### ISSUE TITLE
getting an error while inpainting

### ISSUE THREAD

**Issue by Darkhydra8788** [epic-miner/epic-miner-Fooocus-Sagemaker-Studio-Lab#1]
Traceback (most recent call last):
  File "/home/studio-lab-user/.conda/envs/fooocus/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/studio-lab-user/.conda/envs/fooocus/lib/python3.10/site-packages/gradio/blocks.py", line 1429, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "/home/studio-lab-user/.conda/envs/fooocus/lib/python3.10/site-packages/gradio/blocks.py", line 1239, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "/home/studio-lab-user/epic-miner-Fooocus-Sagemaker-Studio-Lab/Fooocus/modules/gradio_hijack.py", line 278, in preprocess
    im = processing_utils.decode_base64_to_image(x)
  File "/home/studio-lab-user/.conda/envs/fooocus/lib/python3.10/site-packages/gradio/processing_utils.py", line 59, in decode_base64_to_image
    img = Image.open(BytesIO(base64.b64decode(image_encoded)))
  File "/home/studio-lab-user/.conda/envs/fooocus/lib/python3.10/site-packages/PIL/Image.py", line 3288, in open
    """
  File "/home/studio-lab-user/.conda/envs/fooocus/lib/python3.10/site-packages/PIL/Image.py", line 3274, in _open_core
  File "/home/studio-lab-user/.conda/envs/fooocus/lib/python3.10/site-packages/PIL/ImageFile.py", line 116, in __init__
    self._open()
  File "/home/studio-lab-user/.conda/envs/fooocus/lib/python3.10/site-packages/PIL/PngImagePlugin.py", line 748, in _open
    self.mode = self.png.im_mode
AttributeError: can't set attribute 'mode'
Traceback (most recent call last):
  File "/home/studio-lab-user/.conda/envs/fooocus/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/studio-lab-user/.conda/envs/fooocus/lib/python3.10/site-packages/gradio/blocks.py", line 1429, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "/home/studio-lab-user/.conda/envs/fooocus/lib/python3.10/site-packages/gradio/blocks.py", line 1239, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "/home/studio-lab-user/epic-miner-Fooocus-Sagemaker-Studio-Lab/Fooocus/modules/gradio_hijack.py", line 278, in preprocess
    im = processing_utils.decode_base64_to_image(x)
  File "/home/studio-lab-user/.conda/envs/fooocus/lib/python3.10/site-packages/gradio/processing_utils.py", line 59, in decode_base64_to_image
    img = Image.open(BytesIO(base64.b64decode(image_encoded)))
  File "/home/studio-lab-user/.conda/envs/fooocus/lib/python3.10/site-packages/PIL/Image.py", line 3288, in open
    """
  File "/home/studio-lab-user/.conda/envs/fooocus/lib/python3.10/site-packages/PIL/Image.py", line 3274, in _open_core
  File "/home/studio-lab-user/.conda/envs/fooocus/lib/python3.10/site-packages/PIL/ImageFile.py", line 116, in __init__
    self._open()
  File "/home/studio-lab-user/.conda/envs/fooocus/lib/python3.10/site-packages/PIL/PngImagePlugin.py", line 748, in _open
    self.mode = self.png.im_mode
AttributeError: can't set attribute 'mode'

**Comment by epic-miner** [comment]
This error is occurring because there's an attempt to set the 'mode' attribute on an object where it's not allowed, specifically within the PIL (Python Imaging Library) module. It seems to be happening during the opening of a PNG image file. This could be due to various reasons such as incorrect file format, corrupted file, or a bug in the code trying to process the image.
